Repository PoCInnovation/Pool2023, pull requests merged in 2023-02, with the labels that each got.

#55 P2p/day3
  P2P/day03/README.md
  P2P/day03/SETUP.md
  P2P/day03/interfaces/IVestingPlatform.sol
  P2P/day03/interfaces/IVestingPlatformEvents.sol
  P2P/day03/interfaces/IVestingPlatformFee.sol
Labels: documentation

#61 [ADD] nltk module
  Artificial Intelligence/day04/2 - NLP (NLTK)/NLTK.ipynb
  Artificial Intelligence/day04/2 - NLP (NLTK)/README.md
  Artificial Intelligence/day04/2 - NLP (NLTK)/images/countvec.png
  Artificial Intelligence/day04/2 - NLP (NLTK)/images/data_cleaning.png
  Artificial Intelligence/day04/2 - NLP (NLTK)/images/expected_output_lang.png
  Artificial Intelligence/day04/2 - NLP (NLTK)/images/nn.png
  Artificial Intelligence/day04/2 - NLP (NLTK)/requirements.txt
  Artificial Intelligence/day04/3 - NLP (Spacy)/.gitignore
  Artificial Intelligence/day04/3 - NLP (Spacy)/LICENSE
  Artificial Intelligence/day04/3 - NLP (Spacy)/Part - 1.ipynb
  Artificial Intelligence/day04/3 - NLP (Spacy)/Part - 2.ipynb
  Artificial Intelligence/day04/3 - NLP (Spacy)/Part - 3.ipynb
  Artificial Intelligence/day04/3 - NLP (Spacy)/README.md
Labels: artificial-intelligence

#58 Ai/day5
  Artificial Intelligence/day05/.gitignore
  Artificial Intelligence/day05/1.Introduction/Q_Learning.ipynb
  Artificial Intelligence/day05/1.Introduction/README.md
  Artificial Intelligence/day05/1.Introduction/REINFORCE.ipynb
  Artificial Intelligence/day05/1.Introduction/assets/fig1.svg
  Artificial Intelligence/day05/1.Introduction/assets/fig10.svg
  Artificial Intelligence/day05/1.Introduction/assets/fig11.svg
  Artificial Intelligence/day05/1.Introduction/assets/fig12.svg
  Artificial Intelligence/day05/1.Introduction/assets/fig13.svg
  Artificial Intelligence/day05/1.Introduction/assets/fig14.gif
  Artificial Intelligence/day05/1.Introduction/assets/fig15.svg
  Artificial Intelligence/day05/1.Introduction/assets/fig16.svg
  Artificial Intelligence/day05/1.Introduction/assets/fig2.svg
  Artificial Intelligence/day05/1.Introduction/assets/fig3.svg
  Artificial Intelligence/day05/1.Introduction/assets/fig4.svg
  Artificial Intelligence/day05/1.Introduction/assets/fig5.svg
  Artificial Intelligence/day05/1.Introduction/assets/fig6.svg
  Artificial Intelligence/day05/1.Introduction/assets/fig7.svg
  Artificial Intelligence/day05/1.Introduction/assets/fig8.svg
  Artificial Intelligence/day05/1.Introduction/assets/fig9.svg
  Artificial Intelligence/day05/1.Introduction/envi.py
  Artificial Intelligence/day05/2.GoingDeeper/README.md
  Artificial Intelligence/day05/2.GoingDeeper/assets/fig1.gif
  Artificial Intelligence/day05/2.GoingDeeper/assets/fig2.svg
  Artificial Intelligence/day05/2.GoingDeeper/assets/fig3.svg
  Artificial Intelligence/day05/2.GoingDeeper/assets/fig4.svg
  Artificial Intelligence/day05/2.GoingDeeper/assets/fig5.svg
  Artificial Intelligence/day05/2.GoingDeeper/assets/fig6.svg
  Artificial Intelligence/day05/2.GoingDeeper/assets/fig7.svg
  Artificial Intelligence/day05/README.md
  Artificial Intelligence/day05/requirements.txt
Labels: artificial-intelligence

#46 Day3 AI : PyTorch & CNN
  Artificial Intelligence/day03/1 - PyTorch/1.What_Is_PyTorch.ipynb
  Artificial Intelligence/day03/1 - PyTorch/README.md
  Artificial Intelligence/day03/1 - PyTorch/assets/banner-nn.png
  Artificial Intelligence/day03/1 - PyTorch/assets/pytorch.png
  Artificial Intelligence/day03/1 - PyTorch/data/air_quality_train.csv
  Artificial Intelligence/day03/2 - Convolutional Neural Network/2. Convolutional_Neural_Network.ipynb
  Artificial Intelligence/day03/2 - Convolutional Neural Network/README.md
  Artificial Intelligence/day03/2 - Convolutional Neural Network/assets/cnn_background.jpeg
  Artificial Intelligence/day03/2 - Convolutional Neural Network/assets/conv.gif
  Artificial Intelligence/day03/2 - Convolutional Neural Network/assets/conv_exemple.png
  Artificial Intelligence/day03/2 - Convolutional Neural Network/assets/full_model.png
  Artificial Intelligence/day03/2 - Convolutional Neural Network/assets/params_exemple.png
  Artificial Intelligence/day03/2 - Convolutional Neural Network/assets/pooling.png
  Artificial Intelligence/day03/2 - Convolutional Neural Network/assets/yolo-background.jpeg
  Artificial Intelligence/day03/LICENSE
  Artificial Intelligence/day03/README.md
Labels: enhancement

#62 [RM] ai/day3 final parts
  Artificial Intelligence/day03/1 - PyTorch/1.What_Is_PyTorch.ipynb
  Artificial Intelligence/day03/2 - Convolutional Neural Network/2. Convolutional_Neural_Network.ipynb
Labels: artificial-intelligence

#59 feat: added readme day2 p2p
  P2P/day02/README.md
  README.md
Labels: enhancement

#64 Ai/day4 AutoML
  Artificial Intelligence/day04/2 - NLP/NLP.ipynb
  Artificial Intelligence/day04/2 - NLP/README.md
  Artificial Intelligence/day04/2 - NLP/images/countvec.png
  Artificial Intelligence/day04/2 - NLP/images/data_cleaning.png
  Artificial Intelligence/day04/2 - NLP/images/expected_output_lang.png
  Artificial Intelligence/day04/2 - NLP/images/nn.png
  Artificial Intelligence/day04/2 - NLP/requirements.txt
  Artificial Intelligence/day04/3 - AutoML/README.md
  Artificial Intelligence/day04/3 - AutoML/tabular.ipynb
  Artificial Intelligence/day04/3 - AutoML/time_series.ipynb
  Artificial Intelligence/day04/3 - NLP (Spacy)/.gitignore
  Artificial Intelligence/day04/3 - NLP (Spacy)/LICENSE
  Artificial Intelligence/day04/3 - NLP (Spacy)/Part - 1.ipynb
  Artificial Intelligence/day04/3 - NLP (Spacy)/Part - 2.ipynb
  Artificial Intelligence/day04/3 - NLP (Spacy)/Part - 3.ipynb
  Artificial Intelligence/day04/3 - NLP (Spacy)/README.md
Labels: enhancement

#54 P2p/day5
  P2P/day05/README.md
  P2P/day05/SETUP.md
  P2P/day05/scripts/validate
  P2P/day05/utils/POC_01_black.png
  P2P/day05/utils/infographic-1.pdf
  P2P/day05/utils/infographic-2.pdf
  scripts/validate
Labels: documentation

#65 fix(db): postgres root problems on some distribs
  Software/day02/1 - SQL/README.md
Labels: documentation, enhancement

#66 [FIX] subject problems throughout the week
  Artificial Intelligence/day01/1 - python/Python.ipynb
  Artificial Intelligence/day01/1 - python/README.md
  Artificial Intelligence/day02/1 - Maths & Numpy/mathematics-and-numpy.ipynb
  Artificial Intelligence/day02/2 - Neuron from scratch/submit/my_neuron.py
  Artificial Intelligence/day02/2 - Neuron from scratch/submit/nfs.zip
  Artificial Intelligence/day02/2 - Neuron from scratch/tips/LICENSE
  Artificial Intelligence/day02/2 - Neuron from scratch/tips/README.md
  Artificial Intelligence/day02/2 - Neuron from scratch/tips/SETUP.md
  Artificial Intelligence/day02/2 - Neuron from scratch/tips/submit/neuron.ipynb
  Artificial Intelligence/day02/2 - Neuron from scratch/tips/submit/utils.py
  Artificial Intelligence/day04/2 - NLP/NLP.ipynb
  Artificial Intelligence/day04/2 - NLP/README.md
  Artificial Intelligence/day05/1.Introduction/Q_Learning.ipynb
  Artificial Intelligence/day05/1.Introduction/envi.py
Labels: artificial-intelligence

#67 Adding security day
  .github/assets/result.png
  Security/Readme.md
  Security/day01/Readme.md
  Security/day01/first_part/1-Report/Readme.md
  Security/day01/first_part/2-DNS/.gitkeep
  Security/day01/first_part/2-DNS/Readme.md
  Security/day01/first_part/3-HTTPS/Readme.md
  Security/day01/first_part/4-Log/Readme.md
  Security/day01/first_part/4-Log/log.txt
  Security/day01/second_part/Readme.md
  Security/day01/second_part/exploit.pcap
  Security/day01/second_part/keyboard.pcap
  Security/day02/Curious/Readme.md
  Security/day02/Curious/curious
  Security/day02/Gladiator/Readme.md
  Security/day02/Gladiator/gladiator
  Security/day02/Hbin/Hbin
  Security/day02/Hbin/Readme.md
  Security/day02/Inside/Readme.md
  Security/day02/Inside/inside
  Security/day02/Readme.md
  Security/day02/Rox/Readme.md
  Security/day02/Rox/rox
  Security/day02/Snake/Readme.md
  Security/day02/Snake/snake
  Security/day03/README.md
  Security/day04/Blending/Readme.md
  Security/day04/Collision/Readme.md
  Security/day04/Curve/Readme.md
  Security/day04/Hamac/Readme.md
  Security/day04/Readme.md
  Security/day04/Shanon/Readme.md
  Security/day04/Shuffle/Readme.md
  Security/day04/Solidity/Readme.md
  Security/day04/Unknown/Readme.md
  Security/day05/Readme.md
  Security/rush/Readme.md
Labels: enhancement
